# Generated by Django 3.0.4 on 2020-03-23 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('handyman', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('day', models.DateTimeField(auto_now_add=True)),
                ('ticket_number', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(choices=[('Interior', 'Interior'), ('Exterior', 'Exterior')], default='Exterior', max_length=26)),
                ('type', models.CharField(choices=[('Plumbing', 'Plumbing'), ('Electrical', 'Electrical'), ('Heating', 'Heating'), ('Air Conditioning', 'Air Conditioning'), ('Flooring', 'Flooring'), ('Cabinets', 'Cabinets'), ('Door', 'Door'), ('Roof', 'Roof'), ('Siding', 'Siding'), ('Windows', 'Windows'), ('Cement', 'Cement'), ('Gutters', 'Gutters'), ('Other', 'Other')], default='Other', max_length=26)),
                ('problem', models.TextField(max_length=255)),
                ('ticket_open', models.BooleanField(default=True)),
                ('assigned_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='handyman.HandyMan', to_field='username')),
            ],
            options={
                'verbose_name': 'My Ticket',
                'verbose_name_plural': 'My Tickets',
            },
        ),
        migrations.CreateModel(
            name='TicketStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Queue', 'Queue'), ('Assigned', 'Assigned'), ('In Progress', 'In Progress'), ('Awaiting', 'Awaiting'), ('Completed', 'Completed'), ('Closed', 'Closed')], default='Queue', max_length=26)),
                ('reason', models.TextField(default='Ticket Created', max_length=255)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.Ticket')),
            ],
            options={
                'verbose_name': 'My Ticket Status',
                'verbose_name_plural': 'My Tickets Status',
            },
        ),
    ]
